# Config https://docs.astral.sh/ruff/configuration/
line-length = 120
indent-width = 4
exclude = ["*.ipynb"]

# Assume Python 3.12
target-version = "py312"

[lint]
ignore = ["E501", "B008"]  # B008: FastAPI uses Depends() and File() in defaults, which is correct
fixable = ["ALL"]
unfixable = []
select = ["E", "F", "UP", "B", "SIM", "I", "N"]
