services:
  web-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    ports:
      - "5173:5173"
    depends_on:
      - web-backend
  web-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_DB_FILE: /run/secrets/db_name
    ports:
      - "5432:5432"
    volumes:
      - /mnt/pg-data:/var/lib/postgresql/data

secrets:
  db_password:
    file: secrets/db_password.txt
  db_user:
    file: secrets/db_user.txt
  db_name:
    file: secrets/db_name.txt
